[PQ.EX]
version = 1.0
type = "ex-kernel"
zero = 0

pq.rule = "Pflegt Vectoren, Module, Titel und OneDrive-Routing"
pq.mode = ["a","b","c","ab","r"]

pq.bind.ex     = "EX"          # EX-Schicht
pq.bind.matrix = "matrix9x9"   # EPOCHE
pq.bind.room   = "port.room"   # RAUM
pq.bind.sli    = "SLI.layer"   # SLI-Schicht
pq.bind.data   = "data0"       # Daten
pq.bind.lan    = "lan0"        # Routing
pq.bind.screen = "screen0"     # Anzeige
